[package]
name = "disk_emu"
version = "0.1.0"
authors = ["vladglv <vladglv@users.noreply.github.com>"]
edition = "2018"

[dependencies]
libc = { version = "0.2", features = ["align"] }

[profile.release]
lto = true
panic = 'abort'

[lib]
name = "disk_emu"
crate-type = ["staticlib"]
